# Generated by Django 2.2.2 on 2019-08-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_readcomic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadComic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comicName', models.TextField(db_column='comic_name')),
                ('file', models.TextField()),
            ],
        ),
    ]
