# Generated by Django 2.2.2 on 2019-08-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_readcomic'),
    ]

    operations = [
        migrations.AddField(
            model_name='readcomic',
            name='Name',
            field=models.TextField(db_column='Name', default='', editable=False),
        ),
    ]
