# Generated by Django 2.2.2 on 2019-08-31 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_readcomic_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readcomic',
            name='Name',
        ),
    ]
