# Generated by Django 2.2.2 on 2019-09-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_daredevil_doctor_hulk_ironman_thor'),
    ]

    operations = [
        migrations.CreateModel(
            name='inf1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inf1', models.TextField(db_column='inf_1')),
                ('file', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='inf2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inf2', models.TextField(db_column='inf_2')),
                ('file', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='ReadComic',
        ),
    ]
