# Generated by Django 2.2.2 on 2019-09-04 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190905_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inf1',
            name='inf1',
        ),
        migrations.RemoveField(
            model_name='inf2',
            name='inf2',
        ),
    ]
