# Generated by Django 2.2.2 on 2019-09-04 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190905_0114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inf1',
            old_name='file',
            new_name='src',
        ),
        migrations.RenameField(
            model_name='inf2',
            old_name='file',
            new_name='src',
        ),
    ]
