# Generated by Django 2.2.2 on 2019-09-07 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_thongke'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thongke',
            name='name',
            field=models.IntegerField(),
        ),
    ]
