# Generated by Django 3.0 on 2020-01-02 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20190907_0737'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Thongke',
        ),
    ]
